import type { GearCategory, GearItem } from "./siteContent";

const item = (name: string, note: string, role?: string, status: GearItem["status"] = "active"): GearItem => ({ name, note, role, status });

const fullGearCategories: GearCategory[] = [
  { category: "Computers", items: [
    item("AMD Radeon RX 6600 8 GB", "An efficient RDNA 2 1080p-class GPU with 8 GB of VRAM and good Linux-driver fit. Its exact board identity and current assignment still need checking."),
    item("Apple Mac mini (M4, 2024)", "A quiet, power-efficient M4 desktop with 16 GB unified memory and 256 GB-class storage. It is the machine Hermes runs from today.", "Hermes client / daily workstation"),
    item("Apple MacBook Air (M2)", "A 13-inch M2 MacBook Air with 24 GB unified memory and 1 TB storage. It is the lightweight class and coursework machine rather than a sustained graphics or gaming system.", "School laptop"),
    item("Apple MacBook Pro (M4 Pro)", "A 16-inch 2024 MacBook Pro with M4 Pro, 24 GB unified memory, and 512 GB storage. It is the strongest general macOS workstation in the laptop fleet.", "Main general-use laptop"),
    item("ASUS ROG Flow Z13 (2025)", "A 13.4-inch Windows gaming tablet built around Ryzen AI Max and Radeon 8060S graphics, with a 180 Hz touch display, USB4, HDMI 2.1, and a 70 Wh battery.", "Gaming tablet"),
    item("ASUS ROG Zephyrus G14", "A compact 2025 G14 that is the portable Windows performance machine between the fixed desktop and smaller utility laptops. The 2 TB SSD is a user upgrade.", "Main gaming laptop"),
    item("Beelink SER8", "A compact Ryzen 7 8845HS Linux mini PC: far more capable than a utility box, but more power- and space-efficient than the P520 for light always-on services.", "Linux mini PC"),
    item("CHUWI MiniBook X", "A tiny convertible Windows laptop for portable troubleshooting, web or serial configuration, and quick diagnostics. The exact memory variant still needs physical verification.", "Troubleshooting laptop"),
    item("Creekwood", "The main fixed desktop: Ryzen 7 5800X3D, RTX 5080 Founders Edition, 64 GB DDR4, and a large mixed fast/bulk storage footprint. It handles high-end gaming and local desktop workloads.", "Main desktop"),
    item("Dell Alienware m16 (Ryzen 9, GeForce RTX 4080)", "A desk-tethered 16-inch desktop-class gaming laptop with Ryzen 9, RTX 4080, and a QHD 240 Hz display. It is more novelty big-screen rig than primary laptop.", "Big-screen gaming rig"),
    item("Desktop PC (Core i7-6700K, GeForce GTX 1070 Ti)", "An older but usable 1080p/legacy gaming desktop. It is stronger than the older RX 5500 XT and GTX 780 Ti systems, but secondary to the current gaming fleet."),
    item("Desktop PC (Core i7-9700K, GPU Unconfirmed)", "A useful 8-core i7-9700K platform with modest SSD-plus-HDD storage. Its present GPU status is unresolved, so its eventual role is still open."),
    item("Desktop PC (Core i9-12900K, GeForce RTX 4080)", "An owned Gigabyte prebuilt with i9-12900K and a Gigabyte RTX 4080—the only DDR5 desktop in the collection. It overlaps with Creekwood and is currently lent out.", undefined, "lent"),
    item("Framework Laptop 13", "A repairable i7-1260P / 32 GB Omarchy Linux laptop with a 1 TB encrypted Btrfs system, tuned for terminal, development, and touchpad-driven workspace use.", "Main Linux laptop"),
    item("Lenovo ThinkPad T480", "A flexible compatibility workhorse: modern enough for practical Windows/Linux tasks, old enough to risk on experiments, and set up to dual boot Windows and Omarchy.", "Compatibility workhorse"),
    item("Lenovo ThinkPad X1 Carbon Gen 6", "An older thin ThinkPad likely headed for sale. Its exact CPU, display, memory, storage, battery, and cosmetic condition still determine its final usefulness.", undefined, "sale-planned"),
    item("Lenovo ThinkPad X1 Carbon Gen 9", "A four-unit bulk purchase rather than one precisely inventoried laptop. One is in use; the rest need per-unit verification before the keep-or-sell decision.", "Bulk purchase; one in use", "sale-planned"),
    item("Lenovo ThinkPad X220 Tablet", "An intentionally low-risk old convertible for learning NixOS and experimenting with tablet-era hardware. Its value is reproducible rebuild practice, quirks, and safe experimentation.", "NixOS learning project"),
    item("Lenovo ThinkPad Yoga 260", "The newer of the older convertible ThinkPads, associated with bare Arch Linux practice. It overlaps with the X220 Tablet as an experimental convertible.", "Older Linux laptop"),
    item("Lenovo ThinkStation P520", "The active Proxmox homelab server and NAS/media/self-hosting platform. Its actual configuration includes fast storage, a three-HDD RAIDZ pool, and RTX 3060 passthrough for local AI and transcoding experiments.", "Homelab server"),
    item("Minisforum V3", "A Windows 3-in-1 that works as tablet, keyboarded laptop, or portable monitor through DisplayPort input. Its 14-inch high-refresh touch display and USB4 make it unusually flexible for travel and troubleshooting.", "Portable tablet / secondary monitor"),
    item("Minisforum X1 Lite", "A compact Ryzen 7 255 mini PC with Radeon 780M graphics, user-expandable DDR5, dual M.2 storage, 2.5 GbE, USB4, and OCuLink expansion. It is the semi-permanent CAD and general-use machine at the Uline desk."),
    item("NVIDIA GeForce RTX 2060 6 GB", "A redundant standalone GPU: still useful for budget 1080p gaming, NVENC, or a low-cost CUDA build, but constrained by 6 GB of VRAM and no longer the P520 GPU.", undefined, "available"),
    item("Panasonic Let's Note SV1", "A compact JIS-keyboard laptop for Japanese learning, note-taking, visual novels, and Linux experimentation. It is an 11th-gen Tiger Lake machine, with NixOS or Arch/Hyprland still under consideration.", "Japanese-learning laptop"),
    item("Raspberry Pi 4 Model B", "The low-power infrastructure companion to the P520: useful for DNS, monitoring, Tailscale/Wake-on-LAN support, or a voice-assistant endpoint when larger machines are offline.", "Homelab helper"),
    item("Razer Blade Stealth 13", "A compact secondary Windows gaming ultrabook for compatibility and lighter games. Its GTX 1650 Ti Max-Q is clearly secondary to the 2025 G14, while the 1 TB storage is a user upgrade.", "Gaming ultrabook"),
    item("SFF PC (Ryzen 5 3600, Radeon RX 9060 XT)", "The smaller and older of the two Radeon SFF Bazzite PCs, in an NCASE M1. The RX 9060 XT 16 GB offers useful VRAM, while the Ryzen 5 3600 and 16 GB system RAM cap its headroom. It is currently lent out.", undefined, "lent"),
    item("SFF PC (Ryzen 5 5600, Radeon RX 9070 XT)", "The stronger Radeon SFF Bazzite machine: a compact Ryzen 5 5600 / RX 9070 XT build in a KXRORS S300, used as the living-room Steam machine under the TV.", "Living-room Steam machine"),
  ] },
  { category: "Mobile Devices", items: [
    item("Apple iPad mini (6th Generation)", "A 64 GB Wi-Fi iPad mini with A15, USB-C, and an 8.3-inch display. It is the compact tablet for reading, media, and reference use."),
    item("Apple iPad Pro 11-inch (M4, Cellular)", "The primary carry tablet: an 11-inch cellular M4 iPad Pro with tandem OLED, Thunderbolt/USB 4, Apple Pencil Pro support, and 256 GB storage."),
    item("Apple iPad Pro 12.9-inch (M2, Wi-Fi)", "A larger 128 GB Wi-Fi M2 iPad Pro for display-focused tablet work. It complements the smaller cellular M4 iPad and is currently lent out.", undefined, "lent"),
    item("Apple iPhone 13 mini", "The compact modern iPhone in the mobile group. Its Lightning connector separates it from the newer USB-C chain, and it also works as a pocketable audio source.", "Mobile audio source"),
    item("Apple iPhone 17", "A sealed 256 GB black iPhone 17 planned for sale. The personal inventory story is its unopened condition and carrier lock rather than a configuration gap.", undefined, "sale-planned"),
    item("Apple iPhone Air", "The thin, modern USB-C iPhone in the loadout, used as a mobile audio/source device. The exact storage and finish are still unrecorded.", "Mobile audio source"),
    item("Apple iPhone SE (1st Generation)", "The legacy compact iPhone: most useful for tiny size, Lightning-era compatibility, and direct wired headphones through its built-in 3.5 mm jack.", "Legacy iPhone"),
    item("Apple iPhone X", "An older Face ID-era OLED iPhone, kept as a spare/legacy iOS device or app-compatibility test phone. Battery and storage state matter more than family specs.", "Legacy iPhone"),
    item("Google Pixel 4 XL", "A 64 GB large Android phone in decent condition. It works best as a secondary Android, compatibility-check, media, or audio-source device."),
    item("Google Pixel 5", "A compact 8 GB / 128 GB Android phone, practical as an Android test device, secondary phone, or portable audio source.", "Mobile audio source"),
    item("Razer Edge", "The Wi-Fi Razer Edge: Snapdragon G3x Gen 1, 6 GB RAM, 128 GB storage, 6.8-inch 144 Hz AMOLED, and Kishi V2 Pro controls. It is an Android gaming, emulation, streaming, and media endpoint.", "Mobile gaming / audio source"),
  ] },
  { category: "Gaming", items: [
    item("8BitDo SN30 Pro", "A compact retro-inspired controller for travel and 2D/classic games, with modern sticks, triggers, rumble, motion support, USB-C, and Bluetooth. The exact revision is still unconfirmed."),
    item("8BitDo Ultimate 2C", "A lightweight modern controller family with Hall Effect sticks and triggers, remappable shoulder buttons, and low-latency 2.4 GHz support. The owned variant still needs confirmation."),
    item("ASUS ROG Ally", "A Ryzen Z1 Extreme / 16 GB / 512 GB Windows gaming handheld. It remains capable, but is redundant beside the preferred Steam Deck OLED.", "Gaming handheld", "sale-planned"),
    item("Logitech G ASTRO A50 (Gen 5)", "A wireless gaming headset and base-station system built around fast switching between multiple USB audio sources. This Gen 5 model is about PLAYSYNC Audio and Bluetooth mixing, not HDMI video passthrough."),
    item("Meta Quest 3", "A 128 GB standalone mixed-reality/VR headset for standalone VR/MR and optional PC VR. It is a possible sale candidate.", undefined, "available"),
    item("Microsoft Xbox Elite Wireless Controller Series 2", "The premium configurable controller in the Xbox/PC stack. Its practical value depends on stick and bumper condition plus the presence of the accessory kit."),
    item("Microsoft Xbox One", "The original Xbox One, now a compatibility/media console rather than a modern performance machine. It still covers older libraries, discs, Blu-ray, and backward compatibility."),
    item("Microsoft Xbox Wireless Controller (Series X-S)", "Two standard Series X|S-generation controllers: the normal multiplayer and backup counterpart to the Elite Series 2, with broad Xbox/PC/mobile compatibility."),
    item("Nintendo DSi XL (Super Mario Bros. 25th Anniversary, Modded)", "A software-modded red Super Mario Bros. 25th Anniversary DSi XL. The special edition, mod status, and condition/accessory completeness drive its personal inventory story."),
    item("Nintendo New 3DS (Modded)", "A compact software-modded legacy Nintendo handheld. It is distinct from the XL by form factor and from the generic 3DS family by the New 3DS hardware additions."),
    item("Nintendo New 3DS XL (Modded)", "The large software-modded 3DS-family handheld and main legacy Nintendo device for 3DS-era play. Its exact special edition, screen state, hinge state, and region remain open."),
    item("Nintendo Switch (Modded)", "A software-modded original-family Switch: a homebrew and experimental legacy Nintendo device, kept separate from the clean Switch 2 setup."),
    item("Nintendo Switch 2", "The clean current-generation Nintendo console for new releases, multiplayer, and current Nintendo play, with 256 GB internal storage and microSD Express expansion."),
    item("Nintendo Switch 2 Pro Controller", "The primary full-size controller for the Switch 2 dock setup, with Switch 2-specific controls such as the C Button, GameChat, GL/GR rear buttons, HD rumble 2, and a headset jack."),
    item("Nintendo Switch Lite (Modded)", "A compact handheld-only Switch with a modchip and shell swap. It is the smallest portable Switch-family homebrew/travel device in the collection."),
    item("Nintendo Switch OLED Model (Modded)", "A modchip-equipped OLED Switch: the strongest older-Switch-family portable experience here, with OLED screen quality and homebrew flexibility."),
    item("Nintendo Switch Pro Controller", "The original Switch-family full-size controller for docked and local multiplayer play. It is currently borrowed out.", undefined, "lent"),
    item("Valve Steam Deck OLED", "The main gaming handheld, with a user-confirmed 2 TB aftermarket NVMe upgrade. It is the low-friction SteamOS choice for couch play and travel, while the Ally keeps the Windows-compatibility edge.", "Main gaming handheld"),
  ] },
  { category: "Displays & Home Theater", items: [
    item("Acer PM161Q Jbmiuux Portable Monitor", "A straightforward 15.6-inch FHD IPS portable monitor with Mini HDMI, USB-C, low weight, and VESA mounting. It is for server-console and wallboard work rather than color-critical, HDR, or gaming use."),
    item("Apple TV 4K (3rd Generation, 64 GB)", "A fast A15-based living-room source for the older Sony X850G, bringing current streaming apps, Apple ecosystem features, and modern HDR support. This 64 GB Wi-Fi model does not have Ethernet or Thread."),
    item("BenQ ZOWIE XL2411P", "An older esports-oriented 1080p/144 Hz TN monitor. Its responsiveness, low input lag, and adjustability make it a good spare gaming or troubleshooting display beside newer Odyssey screens.", undefined, "stored"),
    item("Dell E773c", "A 17-inch VGA CRT used as a workbench side monitor for the Minisforum X1 Lite at the Uline desk.", "Workbench CRT"),
    item("Samsung 1080p 120 Hz Monitor (Model Unknown)", "A functional Samsung 1080p/120 Hz spare display whose exact model is still unknown. It is a low-stakes auxiliary screen for bench work, troubleshooting, or extra desktop output.", undefined, "lent"),
    item("Samsung Odyssey G4 (25-inch)", "A compact high-refresh 1080p IPS gaming monitor that adds VRR support and 240 Hz refresh over the older BenQ. It is currently lent out.", undefined, "lent"),
    item("Samsung Odyssey G7 (32-inch)", "A fast QHD curved VA gaming monitor: high refresh, lower GPU load than 4K, and better native contrast than IPS. Its sharp curve and variable-refresh quirks make it strongest for gaming. It is currently lent out.", undefined, "lent"),
    item("Samsung Odyssey OLED G8 (G80SD)", "A 32-inch 4K/240 Hz OLED for high-end gaming, HDR media, and sharp desktop use. It is the obvious display match for Creekwood, with normal OLED care needed around static UI.", "Main 4K OLED"),
    item("Sony BRAVIA X850G (75-inch)", "A large older 4K Android TV that still works well for bright-room living-room media and gaming, especially with an Apple TV handling streaming."),
    item("Sony WEGA KV-20FS12", "A 20-inch flat-glass Trinitron CRT TV paired with a Raspberry Pi 4 for retro gaming and video playback at true 240p/480i.", "Retro CRT display"),
  ] },
  { category: "Audio", items: [
    item("Apple AirPods Max (1st Generation)", "A premium Apple-ecosystem ANC headphone for convenient wireless and travel listening. The wired open-backs cover stationary reference use, while this pair prioritizes ANC, transparency, controls, and integration."),
    item("Apple AirPods Pro 3", "Feature-dense everyday earbuds: strong ANC, health and hearing features, Apple-device integration, and a pocketable form factor. They are the low-friction daily-carry complement to wired IEMs."),
    item("Apple USB-C to 3.5 mm Headphone Jack Adapter", "A tiny convenience DAC that is surprisingly clean for efficient IEMs. Its job is easy portable wired output, not power-hungry desktop listening."),
    item("Audeze LCD-X", "A high-end open-back planar for studio and critical listening, with strong build and low distortion. It is resolving but heavy, leaky, and meant for a quiet desk rather than casual portable use."),
    item("Beats Powerbeats Pro 2", "The secure-fit workout earbuds: they trade AirPods Pro pocketability for ear hooks, physical volume controls, and longer sport-session confidence."),
    item("FiiO K13 R2R", "The desk hub for wired headphones: a feature-rich DAC/amp with a deliberately different R2R/NOS path, practical PEQ, multiple outputs, and enough power for stationary listening.", "Headphone DAC / amp"),
    item("Focal Azurys", "A modern, easy-to-drive closed-back passive headphone. It is a lighter, portable, leak-limited alternative to the open-back reference models, not a wireless ANC replacement."),
    item("Fosi Audio GR70", "A small tube headphone amp/preamp for tube flavor, tone controls, and a deliberately non-neutral listening path. It is a character piece rather than a reference amp."),
    item("Fosi Audio ZA3", "A compact, high-value Class-D amp with balanced input, subwoofer output, trigger input, and enough power for bookshelf speakers. It is the power stage behind the WiiM-based stereo chain.", "Stereo amplifier"),
    item("HIFIMAN Edition XS", "The lower-cost large planar: spacious, detailed, and capable at a desk, but not portable or isolation-friendly. It is a useful contrast to the LCD-X and dynamic-driver options."),
    item("KEF Q150", "A compact passive bookshelf speaker with coaxial Uni-Q imaging and useful bass for its size. It is the main passive-speaker building block for both desktop and living-room chains."),
    item("Kiwi Ears x B_Media Chorus", "An inexpensive everyday IEM: easy to carry, detachable-cable friendly, and tuned for warm casual listening rather than maximum technical performance."),
    item("Logitech Z625", "The convenience speaker system: loud, simple, THX-certified, and easy to connect over optical or analog. Its value is friction reduction, not the component flexibility of the WiiM/ZA3/KEF/SVS chain."),
    item("MOONDROP x Crinacle DUSK", "The most feature-rich wired IEM here: a complex hybrid driver setup with both analog and USB-C/DSP use. It is a portable critical-listening option with real tuning flexibility."),
    item("Sennheiser HD 4.50BTNC", "A legacy ANC travel headphone: lower-stakes and compact compared with newer premium wireless pairs, but best kept as a backup rather than the main wireless reference."),
    item("Sennheiser HD 490 PRO", "The pragmatic work headphone: light, open, studio-oriented, and intended for editing, monitoring, and long sessions when isolation is not required."),
    item("Sennheiser HD 660S2", "A comfortable high-impedance dynamic open-back with a warmer, deeper presentation. It pairs naturally with the FiiO K13 R2R for long desk listening sessions."),
    item("Sennheiser MOMENTUM 4 Wireless", "The long-battery, cross-platform ANC over-ear for travel and office use, with app EQ and a warm/bassy sound. It is the flexible alternative when broader codec support matters more than Apple-only integration."),
    item("Sony WF-1000XM4", "An older Sony ANC earbud that still has an Android/high-codec niche through LDAC. It makes most sense for Android-oriented mobile listening rather than Apple-device convenience."),
    item("SVS SB-1000 Pro", "A compact sealed subwoofer with deep extension, app-based tuning, and controlled bass. Placement, crossover, phase, and room correction are part of getting it right."),
    item("TRUTHEAR x Crinacle ZERO RED", "A straightforward value IEM: wired, affordable, measurement-friendly, and a useful contrast against DUSK. Its 10-ohm adapter offers an alternate bass presentation without app or DSP dependency."),
    item("WiiM Ultra", "The modern stereo control center: streamer, DAC/preamp, source selector, room-correction and EQ platform, phono input, TV ARC endpoint, subwoofer manager, and trigger output in one box.", "Streamer / DAC / preamp"),
    item("Yamaha RX-V677", "The older multi-channel receiver path, with HDMI switching, surround decoding, room calibration, phono input, and speaker amplification. It remains useful as a living-room receiver or legacy source hub."),
  ] },
  { category: "Cameras & Lenses", items: [
    item("Fujifilm X-T4", "A stabilized APS-C hybrid body with strong stills ergonomics, dual card slots, and serious 4K modes. It is the flexible creative camera, especially with the XF18-55mm zoom."),
    item("Fujifilm X100VI", "A high-end fixed-lens everyday camera with a 40 MP APS-C sensor, Fujifilm color science, IBIS, and a compact rangefinder-style body. It is the premium carry camera rather than a replacement for interchangeable-lens work."),
    item("Fujifilm X20", "An older premium compact with tactile controls, a bright manual zoom, RAW support, and an optical viewfinder. It overlaps with newer Fujifilm bodies and is likely headed for sale.", undefined, "sale-planned"),
    item("Fujinon XF18-55mmF2.8-4 R LM OIS", "Fujifilm's compact standard zoom: brighter and more capable than a typical kit lens, but portable enough to leave on the X-T4. Its 27–84 mm-equivalent range makes it a sensible everyday/travel pairing."),
    item("Panasonic Lumix DMC-ZS50", "A travel-zoom compact whose 24–720 mm-equivalent lens prioritizes reach over large-sensor image quality. It is a pocketable specialist for daylight travel and casual telephoto scenes."),
  ] },
  { category: "Test Equipment", items: [
    item("HP 54600B", "A 100 MHz, 2-channel digital storage oscilloscope with auto-scale, cursors, and storage. It is the measurement workhorse on the electronics bench.", "Bench oscilloscope"),
    item("Tektronix 465B", "A 100 MHz, 2-channel analog oscilloscope from the late 1970s. It is the vibe and XY instrument of the bench, kept for the oscilloscope-music side of the hobby.", "Analog oscilloscope"),
  ] },
  { category: "Accessories & Network", items: [
    item("5-Port Gigabit Ethernet Switch (Model Unknown)", "An owned but unidentified 5-port gigabit edge switch. It is for devices that do not benefit from the 2.5GbE core, not the NAS or workstation backbone."),
    item("8BitDo Wireless Keyboard", "An 87-key retro-styled mechanical keyboard with hot-swap PCB, Kailh Box White V2 switches, dye-sub PBT caps, tri-mode connectivity, and programmable Dual Super Buttons."),
    item("Anker Thunderbolt 5 Dock", "A 14-in-1 high-bandwidth desk dock with 140 W host power delivery, two downstream Thunderbolt 5 ports, 2.5 GbE, SD and TF readers, and selectable HDMI 2.1 or DisplayPort 2.1 output."),
    item("BrosTrend 8-Port 2.5G Ethernet Switch", "The main multi-gig wired switch for the P520 homelab network. The exact variant still needs confirmation, but its role is the fanless 2.5GbE wired core."),
    item("Google Nest Wifi (AC2200)", "The existing Wi-Fi layer, kept behind the faster wired core rather than between the NAS and high-throughput clients. Its gigabit wired ports make it a coverage device, not the network backbone."),
    item("HHKB Pro 2", "A compact wired 60-key keyboard built around Topre electrostatic capacitive switches and a modified ANSI layout. Its exact color, legends, and regional model still need confirmation."),
    item("iPad Magic Keyboard (M4)", "A floating iPad keyboard case with backlit scissor keys, a large haptic glass trackpad, function row, USB-C pass-through charging, and front/back protection."),
    item("Keychron Q1", "A premium wired 75% custom mechanical keyboard platform with QMK/VIA programmability, an aluminum case, rotary-encoder variants, and replaceable components."),
    item("Kiwi Ears x B_Media Terras Cable", "A modular 0.78 mm 2-pin IEM replacement cable that supports 3.5 mm analog, 4.4 mm balanced, and USB-C source paths. It is a connectivity convenience, not a guaranteed sonic upgrade."),
    item("Logitech Combo Touch for iPad Pro (M2)", "A detachable keyboard case and kickstand system with Smart Connector power, a backlit keyboard, trackpad, and typing, viewing, sketching, and reading modes."),
    item("Logitech G Pro Wireless", "A lightweight, ambidextrous LIGHTSPEED gaming mouse with a HERO 16K sensor, removable side buttons, onboard profiles, and POWERPLAY compatibility."),
    item("Logitech G Pro X Superlight 2 Dex", "A 60 g right-handed ergonomic LIGHTSPEED mouse with a HERO 2 sensor and LIGHTFORCE hybrid switches, focused on competitive tracking and low weight."),
    item("Logitech G915 TKL", "A low-profile tenkeyless wireless mechanical gaming keyboard with LIGHTSPEED, Bluetooth, per-key RGB, media controls, and a slim aluminum deck."),
    item("Logitech MX Anywhere 3", "A compact rechargeable mouse with Darkfield tracking, MagSpeed scrolling, USB-C, and Easy-Switch for up to three devices. It uses a Unifying receiver or Bluetooth, not Logi Bolt."),
    item("Logitech MX Master 3", "A large right-handed productivity mouse with Darkfield tracking, MagSpeed scrolling, thumb wheel, gesture button, Easy-Switch, and Flow multi-computer control."),
    item("Microsoft Wireless Keyboard", "A slim Bluetooth Microsoft Designer Compact Keyboard with Swift Pair on Windows, pairing for up to three devices, and four replaceable CR2032 batteries."),
    item("Monoprice SlimRun Cat6A 7 ft Patch Cables (10-Pack)", "A tidy short-run Cat6A cable set for the homelab and network desk. The thin 30 AWG design is neat for nearby devices, not the first choice for permanent runs or high-power PoE."),
    item("OWC Thunderbolt 4 Dock", "An 11-port Thunderbolt 4 desk dock with three downstream Thunderbolt ports, four USB ports, gigabit Ethernet, audio, SD, and up to 96 W host power delivery."),
    item("Rainy 75 Pro", "An 81-key 75% aluminum mechanical keyboard with tri-mode connectivity, gasket-style construction, RGB, double-shot PBT keycaps, and a large rechargeable battery."),
    item("Razer Basilisk V3 Pro", "A right-handed ergonomic wireless gaming mouse with a Focus Pro 30K sensor, optical switches, HyperSpeed/Bluetooth/wired connectivity, RGB, and a generous multi-button layout."),
    item("Razer Viper V3 Pro", "A lightweight symmetrical esports mouse with a Focus Pro 35K Gen-2 sensor, HyperSpeed wireless, 8,000 Hz support, USB-C charging, and an onboard profile."),
    item("Xbox Kinect", "A Kinect v2 depth-sensing camera and microphone array for RGB, infrared/depth data, body tracking, and audio input in TouchDesigner and audio-visualizer projects.", "Creative depth camera"),
  ] },
];

const excludedPublicCategories = new Set(["Accessories & Network"]);

export const gearCategories = fullGearCategories.filter(({ category }) => !excludedPublicCategories.has(category));
